version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: global_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: global_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/global_app?authSource=admin
      - JWT_SECRET=supersecretjwt
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: global_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data: