name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 13.217.227.80
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/profesores
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          echo '🚀 Deployment completed successfully'
          echo '🌐 Frontend: http://13.217.227.80:3000'
          echo '🔗 API: http://13.217.227.80:5000/api'
