name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security checks
      run: |
        echo "🔒 Starting security scan..."
        cd backend
        npm audit --audit-level=high || echo "Security scan completed"